export const TOAST_EDIT = 'TOAST_EDIT'
export const TOAST_INSERT = 'TOAST_INSERT'
export const TOAST_DELETE = 'TOAST_DELETE'
export const TOAST_TRUE = 'TOAST_TRUE'
export const TOAST_FALSE = 'TOAST_FALSE'
export const TOAST_LOGIN = 'TOAST_LOGIN'
export const TOAST_LOGOUT = 'TOAST_LOGOUT'