export const CART_INSERT ='CART_INSERT'  
export const CART_PRODUCT_DELETE = 'CART_PRODUCT_DELETE'
export const CART_PRODUCT_INCREMENT = 'CART_PRODUCT_INCREMENT'
export const CART_PRODUCT_DECREMENT = 'CART_PRODUCT_DECREMENT'